# Signal Classifier

## Library Imports

In [5]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import tensorflow as tf
#np.seterr(divide='ignore', invalid='ignore')
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
def plot(fig,x,y,name):
    fig.add_trace(go.Scatter(x=x,y=y,mode='lines',name=name))


## Defintion of Different Signal Functions

In [38]:
SignalsDict={'Box':1,'Saw':2,'Exp':3,'Sin':4,'Gaus':5}
def Generate(signal,x,Amount,normalized=True,jump=False,fourier=False,N=40,M=40,Noise=False,noiseParameter=0.1):
    signalOutput=[]
    length=Amount+2
    print(SignalsDict[signal])
    if(SignalsDict[signal]==1):
        #a=np.linspace(np.pi/4,np.pi/2,len(x))
        a=np.linspace(.10,2.90,length)
        b=np.append(np.linspace(-100,-0.01,int(length/2)),np.linspace(0.01,100,int(length/2)))
        a=np.random.permutation(a)
        b=np.random.permutation(b)
        if fourier:
            for i in range(Amount):
                cn=box(x,a[i],b[i],normalized=normalized,fourier=True,N=N)
                normalization=1#np.max(abs(F))
                #BoxSignal.append(F/normalization)
                #BoxSignalFourier.append(fx)
                signalOutput.append(FourierSeries(cn,x,N,M))
            return [signalOutput,a[0:Amount],b[0:Amount]]
        elif Noise:
            for i in range(Amount):
                F=box(x,a[i],b[i],noise=True,normalized=normalized,noiseParameter=noiseParameter)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount]]
        else:
            for i in range(Amount):
                F=box(x,a[i],b[i],jump=jump,normalized=normalized)
                #normalization=1#np.max(abs(F))
                #BoxSignal.append(F/normalization)
                #BoxSignalFourier.append(fx)
                signalOutput.append(F[0])
            return [signalOutput,a[0:Amount],b[0:Amount]]
    elif(SignalsDict[signal]==2):
        a=np.linspace(np.pi/4,np.pi/2,length)
        b=np.append(np.linspace(-100,-0.01,int(length/2)),np.linspace(0.01,100,int(length/2)))
        a=np.random.permutation(a)
        b=np.random.permutation(b)
        if fourier:
            for i in range(Amount):
                cn=saw(x,a[i],b[i],normalized=normalized
                ,fourier=True,N=N)
                signalOutput.append(FourierSeries(cn,x,N,M))
            return [signalOutput,a[0:Amount],b[0:Amount]]
        elif Noise:
            for i in range(Amount):
                F=saw(x,a[i],b[i],noise=True,normalized=normalized,noiseParameter=noiseParameter)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount]]
        else:
            for i in range(Amount):
                F=saw(x,a[i],b[i],jump=jump,normalized=normalized)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount]]
    elif(SignalsDict[signal]==3):
        a=np.linspace(np.pi/4,np.pi/2,length)
        b=np.append(np.linspace(-1,-0.1,int(length/2)),np.linspace(0.1,1,int(length/2)))
        c=np.append(np.linspace(-3,-1.01,int(length/2)),np.linspace(-1.01,1,int(length/2)))
        a=np.random.permutation(a)
        b=np.random.permutation(b)
        c=np.random.permutation(c)
        if fourier:
            for i in range(Amount):
                cn=exp(x,a[i],b[i],c[i],normalized=normalized
                ,fourier=True,N=N)
                signalOutput.append(FourierSeries(cn,x,N,M))
            return [signalOutput,a[0:Amount],b[0:Amount],c[0:Amount]]
        elif Noise:
            for i in range(Amount):
                F=exp(x,a[i],b[i],c[i],noise=True,normalized=normalized,noiseParameter=noiseParameter)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount],c[0:Amount]]
        else:
            for i in range(Amount):
                F=exp(x,a[i],b[i],c[i],jump=jump,normalized=normalized)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount],c[0:Amount]]
    elif(SignalsDict[signal]==4):
        a=np.linspace(np.pi/4,np.pi/2,length)
        b=np.append(np.linspace(-2*np.pi,-0.3,int(length/2)),np.linspace(0.3,2*np.pi,int(length/2)))
        c=np.append(np.linspace(-100,-0.1,int(length/2)),np.linspace(0.1,100,int(length/2)))
        a=np.random.permutation(a)
        b=np.random.permutation(b)
        c=np.random.permutation(c)
        if fourier:
            for i in range(Amount):
                cn=sinu(x,a[i],b[i],c[i],normalized=normalized
                ,fourier=True,N=N)
                signalOutput.append(FourierSeries(cn,x,N,M))
            return [signalOutput,a[0:Amount],b[0:Amount],c[0:Amount]]
        elif Noise:
            for i in range(Amount):
                F=sinu(x,a[i],b[i],c[i],noise=True,normalized=normalized,noiseParameter=noiseParameter)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount],c[0:Amount]]
        else:
            for i in range(Amount):
                F=sinu(x,a[i],b[i],c[i],jump=jump,normalized=normalized)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount],c[0:Amount]]
    elif(SignalsDict[signal]==5):
        a=np.linspace(np.pi/4,np.pi/2,length)
        #b=np.append(np.linspace(-10,-1,int(length/2)),np.linspace(1,10,int(length/2)))
        b=np.linspace(1,10,length)
        a=np.random.permutation(a)
        b=np.random.permutation(b)

        if fourier:
            for i in range(Amount):
                #x=np.linspace(-np.pi,np.pi,N)
                cn=gaus(x,a[i],int(b[i]),fourier=True,N=N,M=M)
                fx=FourierSeries(cn,x,M)
                #cn=gaus(x,a[i],int(b[i]),normalized=normalized,fourier=True,N=N,M=M)
                signalOutput.append(fx)
            return [signalOutput,a[0:Amount],b[0:Amount]]
        elif Noise:
            for i in range(Amount):
                F=gaus(x,a[i],int(b[i]),noise=True,normalized=normalized,noiseParameter=noiseParameter)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount]]
        else:
            for i in range(Amount):
                F=gaus(x,a[i],int(b[i]),jump=jump,normalized=normalized)
                signalOutput.append(F)
            return [signalOutput,a[0:Amount],b[0:Amount]]
def FourierSeries(cn,X,N,M=0):
    fx=[]
    #X=np.linspace(-np.pi,np.pi,M)
    '''
    Cn=np.zeros(len(cn))
    Cn[0]=cn[int(N/2)]
    Cn[1:int(N/2)-1]=cn[1:int(N/2)-1]
    Cn[int(N/2)+1:N]=cn[int(N/2)+1:N]
    fx=np.fft.ifft(Cn)
    '''

    for x in X:
        result=0
        for i in range(int((-N/2)),int((N/2))):
            result=result+cn[int(i+(N/2))]*(np.e**(1j*i*x)) #Calculate Fourier Series approximation using formula
        fx.append(result.real)
    return fx

In [13]:
def dft(N,M=40):
    #w=np.e**((2*np.pi*-1j)/N)
    power=np.zeros((M,N),dtype=complex)
    xj = np.linspace(-np.pi, np.pi, N)
    for i in range(M):
        for j in range(N):
            #power[i][j]=((-N/2)+i)*j
            power[i][j] = -1j*(i-M/2)*xj[j]
    #DFT=(w**power)/N
    DFT = np.e**power
    return DFT
def box(x,a=2,b=5,normalized=True,jump=False,noise=False,noiseParameter=0.1,fourier=False,N=40):
    if fourier:
        k=np.linspace(int((-N/2)),int((N/2)),N+1)
        print(k)
        fkhat=np.zeros(len(k))
        fkhat[k==0]=(2*a*b)
        fkhat[k!=0]=((2*b*np.sin(a*k[k!=0]))/k[k!=0])
        y=fkhat/(2*np.pi)
        if normalized:
            return y/np.max(abs(box(x,a,b,normalized=False)))
        return y
    y=np.zeros(len(x))
    y[np.abs(x)<a]=b
    if noise:
        y=y+np.random.normal(0,noiseParameter,len(x))
        if normalized:
            return y/np.max(abs(box(x,a,b,normalized=False)))
        return y
    if normalized:
        if jump:
            y=y/np.max(abs(y))
            fk=np.zeros(len(x))
            print(fk)
            print(a)
            '''
            x=x.round(decimals=1)
            fk[x==a]=y[x==a]
            fk[x==-a]=y[x==-a]
            '''
            fk[np.abs(x-a)<0.01]=y[np.abs(x-a)<0.01]
            fk[np.abs(x+a)<0.01]=y[np.abs(x+a)<0.01]
            print(fk)
            return y,fk
        return y/np.max(abs(y))
    return y
def saw(x,a=2,b=5,normalized=True,jump=False,noise=False,noiseParameter=0.1,fourier=False,N=40):
    if fourier:
        k=np.linspace(int((-N/2)),int((N/2)),N+1)
        fkhat=np.zeros(len(k)).astype(complex)
        fkhat[k==0]=0
        fkhat[k!=0]=(2*1j*b*(np.sin(a*k[k!=0])-a*k[k!=0]*np.cos(a*k[k!=0])))/(k[k!=0]**2)
        y=fkhat/(2*np.pi)
        if normalized:
            return y/np.max(abs(saw(x,a,b,normalized=False)))
        return y
    y=np.zeros(len(x))
    y[np.abs(x)<a]=-b*x[np.abs(x)<a]
    if noise:
        y=y+np.random.normal(0,noiseParameter,len(x))
        if normalized:
            return y/np.max(abs(saw(x,a,b,normalized=False)))
        return y
    if normalized:
        if jump:
            y=y/np.max(abs(y))
            fk=np.zeros(len(x))
            print(fk)
            print(a)
            '''
            x=x.round(decimals=1)
            fk[x==a]=y[x==a]
            fk[x==-a]=y[x==-a]
            '''
            fk[np.abs(x-a)<0.01]=y[np.abs(x-a)<0.01]
            fk[np.abs(x+a)<0.01]=y[np.abs(x+a)<0.01]
            print(fk)
            return y,fk
        return y/np.max(abs(y))
    return y
def exp(x,a=2,b=2,c=-1,normalized=True,jump=False,noise=False,noiseParameter=0.1,fourier=False,N=40):
    if fourier:
        k=np.linspace(int((-N/2)),int((N/2)),N+1).astype(complex)
        fkhat=np.zeros(len(k)).astype(complex)
        fkhat[k==0]=(2*((a*b*c)+np.sinh(a*b)))/b
        fkhat[k!=0]=((2*c*np.sin(a*k[k!=0]))/k[k!=0])+((2*np.sinh(a*(b+(1j*k[k!=0]))))/(b+(1j*k[k!=0])))
        y=fkhat/(2*np.pi)
        if normalized:
            return y/np.max(abs(exp(x,a,b,c,normalized=False)))
        return y
    y=np.zeros(len(x))
    y[np.abs(x)<a]=c+np.e**(-b*x[[np.abs(x)<a]])
    if noise:
        y=y+np.random.normal(0,noiseParameter,len(x))
        if normalized:
           return y/np.max(abs(exp(x,a,b,c,normalized=False)))
        return y
    if normalized:
        if jump:
            y=y/np.max(abs(y))
            fk=np.zeros(len(x))
            print(fk)
            print(a)
            '''
            x=x.round(decimals=1)
            fk[x==a]=y[x==a]
            fk[x==-a]=y[x==-a]
            '''
            fk[np.abs(x-a)<0.01]=y[np.abs(x-a)<0.01]
            fk[np.abs(x+a)<0.01]=y[np.abs(x+a)<0.01]
            print(fk)
            return y,fk
        return y/np.max(abs(y))
    return y
def sinu(x,a=2,b=2,c=-1,normalized=True,jump=False,noise=False,noiseParameter=0.1,fourier=False,N=40):
    if fourier:
        k=np.linspace(int((-N/2)),int((N/2)),N+1).astype(complex)
        fkhat=np.zeros(len(k)).astype(complex)
        fkhat[k==b]=((1j*c*np.sin(2*a*b))/(2*b))-(1j*a*c)
        fkhat[k==-b]=(1/2)*1j*c*((2*a)-((np.sin(2*a*b))/b))
        fkhat[k!=b]=(2*1j*c*((b*np.cos(a*b)*np.sin(a*k[k!=b]))-(k[k!=b]*np.sin(a*b)*np.cos(a*k[k!=b]))))/((b**2)-(k[k!=b]**2))
        y=fkhat/(2*np.pi)
        if normalized:
            return y/np.max(abs(sinu(x,a,b,c,normalized=False)))
        return y
    y=np.zeros(len(x))
    y[np.abs(x)<a]=c*np.sin(b*x[np.abs(x[0:1500])<a])
    if noise:
        y=y+np.random.normal(0,noiseParameter,len(x))
        if normalized:
            return y/np.max(abs(sinu(x,a,b,c,normalized=False)))
        return y
    if normalized:
        if jump:
            y=y/np.max(abs(y))
            fk=np.zeros(len(x))
            print(fk)
            print(a)
            '''
            x=x.round(decimals=1)
            fk[x==a]=y[x==a]
            fk[x==-a]=y[x==-a]
            '''
            fk[np.abs(x-a)<0.01]=y[np.abs(x-a)<0.01]
            fk[np.abs(x+a)<0.01]=y[np.abs(x+a)<0.01]
            print(fk)
            return y,fk
        return y/np.max(abs(y))
    return y
def gaus(x,a=2,b=2,normalized=True,jump=False,noise=False,noiseParameter=0.1,fourier=False,N=40,M=40):
    if fourier:
        fkhat=((np.dot(dft(N,M),gaus(x,a,b)))/N)
        if normalized:
            return fkhat/np.max(abs(gaus(x,a,b,normalized=False)))
        return fkhat
    y=np.zeros(len(x))
    y[np.abs(x)<a]=np.e**(-a*(x[np.abs(x)<a]**(2*b)))
    y=np.nan_to_num(y)
    if noise:
        y=y+np.random.normal(0,noiseParameter,len(x))
        if normalized:
            return y/np.max(abs(gaus(x,a,b,normalized=False)))
        return y
    if normalized:
        if jump:
            y=y/np.max(abs(y))
            fk=np.zeros(len(x))
            print(fk)
            print(a)
            '''
            x=x.round(decimals=1)
            fk[x==a]=y[x==a]
            fk[x==-a]=y[x==-a]
            '''
            fk[np.abs(x-a)<0.01]=y[np.abs(x-a)<0.01]
            fk[np.abs(x+a)<0.01]=y[np.abs(x+a)<0.01]
            print(fk)
            return y,fk
        return y/np.max(abs(y))
    return y
def FourierSeries(cn,X,N,M=0):
    fx=[]
    #X=np.linspace(-np.pi,np.pi,M)

    result=0
    for x in X:
        result=0
        for i in range(int((-N/2)),int((N/2))):
            result=result+cn[int(i+(N/2))]*(np.e**(1j*i*x)) #Calculate Fourier Series approximation using formula
        fx.append(result.real)
    return fx

In [14]:
N=1500
xx=np.linspace(-np.pi,np.pi,N+1)
x=xx[0:-1]
def et(x,n,sign=1):
    if sign==1:
        return np.e**(1j*x*n)
    else:
        return np.e**(-1j*x*n)

def trigSig(n):

        Sipi=1.85193705198247
        sig=np.pi*np.sin((np.pi*np.abs(n))/(np.max(n)))/Sipi
        return sig
def polySig(n):
    sig=(np.pi*np.abs(n)/np.max(n))
    return sig
def expSig(n):
    alpha=2
    tau=np.linspace(1/np.max(N),1-(1/np.max(N)),1000)
    res=tau[1]-tau[0]
    const = np.pi/( res*sum(np.e**(1/(alpha*tau*(tau-1)))) )
    sig = const*( np.abs(n)/np.max(n) )*np.e**(1/(alpha*(np.abs(n)/max(n))*((np.abs(n)/max(n))-1)));
    sig[n==0]=0
    sig[0]=0
    sig[-1]=0
    return sig

'''
    type determines which fourier coefficient to calculate
        trig:1
        exp:2
        poly:3
'''
def partialFourierSum(M2,M1,x,n,cn,type=1):
    D2=np.zeros((M2-1,M1),dtype=complex)
    for p in range(M2-1):
      for q in range(M1-1):
        D2[p][q]=(et(x[p],n[q]))
    if type==1:
        sig=trigSig(n)
    elif type==2:
        sig=polySig(n)
    elif type==3:
        sig=expSig(n)
    SN=cn*(1j*np.sign(n)*sig)
    fx = np.dot(D2,SN)
    return fx.real
cn=exp(x,3,-2,-100,normalized=True,fourier=True,N=100)
N=[100]
M1=len(cn)
M2=1500
n=np.linspace(-M1/2,M1/2,M1)
h=np.linspace(0,M2-1,M2-1)
X =-np.pi+ (2*np.pi/M2)*h
#x=np.linspace(-5,5,M2-1)
fig=go.Figure()
plot(fig,x,partialFourierSum(M2,M1,x,n,cn,1),'Trig')
plot(fig,x,partialFourierSum(M2,M1,x,n,cn,2),'Poly')
plot(fig,x,partialFourierSum(M2,M1,x,n,cn,3),'Exp')
fig.show()

C:\Users\Abbass\AppData\Local\Temp\ipykernel_25004\2366111458.py:23: RuntimeWarning:

divide by zero encountered in true_divide



## Testing
###

In [16]:
points=1500
Amount=1000
x=np.linspace(-np.pi,np.pi,points)
BoxSignal=Generate('Box',x,Amount=Amount,jump=True)
SawSignal=Generate('Saw',x,Amount=Amount,jump=True)
ExpSignal=Generate('Exp',x,Amount=Amount,jump=True)
SinSignal=Generate('Sin',x,Amount=Amount,jump=True)
GausSignal=Generate('Gaus',x,Amount=Amount,jump=True)

#parameters




1
[0. 0. 0. ... 0. 0. 0.]
1.2692307692307694
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
2.016083916083916
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
2.734965034965035
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
0.6902097902097902
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
1.7363636363636366
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
0.2566433566433567
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
0.4468531468531468
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
0.7573426573426573
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
1.2272727272727273
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
1.3587412587412588
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
2.3461538461538463
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
1.7111888111888112
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
0.7797202797202797
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
1.6636363636363638
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
1.4594405594405595
[0. 0. 0. ... 0. 0.

In [39]:
Signals=[BoxSignal[0][0],SawSignal[0][0],ExpSignal[0][0],SinSignal[0][0],GausSignal[0][0]]
SignalLabels=[
    1*np.ones(Amount),
    2*np.ones(Amount),
    3*np.ones(Amount),
    4*np.ones(Amount),
    5*np.ones(Amount)]
SignalsTrain=np.array(np.concatenate(Signals).flat)
SignalsTrain=SignalsTrain.reshape((Amount*5,1500))
SignalLabelsTrain=np.array(np.concatenate(SignalLabels).flat)

ValueError: cannot reshape array of size 15000 into shape (5000,1500)

In [26]:
print(BoxSignal)

[[(array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])), (array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ...,

In [43]:
fig=go.Figure()
plot(fig,x,Generate('Box',x,Amount=1,jump=True)[0][0],'testing')
fig.show()

1
[0. 0. 0. ... 0. 0. 0.]
0.1
[0. 0. 0. ... 0. 0. 0.]


In [12]:
np.shape(SignalsTrain)

(5000, 1500)

In [7]:
modelNN = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(6)
])
modelNN.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
modelNN.fit(SignalsTrain, SignalLabelsTrain, epochs=100)


Epoch 1/100
157/157 [==============================] - 1s 2ms/step - loss: 0.4752 - accuracy: 0.8112
Epoch 2/100
157/157 [==============================] - 0s 2ms/step - loss: 0.3401 - accuracy: 0.8816
Epoch 3/100
157/157 [==============================] - 0s 2ms/step - loss: 0.2350 - accuracy: 0.9206
Epoch 4/100
157/157 [==============================] - 0s 2ms/step - loss: 0.2135 - accuracy: 0.9228
Epoch 5/100
157/157 [==============================] - 0s 2ms/step - loss: 0.2049 - accuracy: 0.9276
Epoch 6/100
157/157 [==============================] - 0s 2ms/step - loss: 0.1714 - accuracy: 0.9414
Epoch 7/100
157/157 [==============================] - 0s 2ms/step - loss: 0.1814 - accuracy: 0.9364
Epoch 8/100
157/157 [==============================] - 0s 2ms/step - loss: 0.1560 - accuracy: 0.9442
Epoch 9/100
157/157 [==============================] - 0s 2ms/step - loss: 0.1515 - accuracy: 0.9472
Epoch 10/100
157/157 [==============================] - 0s 2ms/step - loss: 0.1723 - accura

In [8]:

BoxSignal=Generate('Box',x,Amount=1000)
SawSignal=Generate('Saw',x,Amount=1000)
ExpSignal=Generate('Exp',x,Amount=1000)
SinSignal=Generate('Sin',x,Amount=1000)
GausSignal=Generate('Gaus',x,Amount=1000)
a=[BoxSignal[1],SawSignal[1],ExpSignal[1],SinSignal[1],GausSignal[1]]
b=[BoxSignal[2],SawSignal[2],ExpSignal[2],SinSignal[2],GausSignal[2]]
c=[np.zeros(1000),np.zeros(1000),ExpSignal[3],SinSignal[3],np.zeros(1000)]
Signals=[BoxSignal[0],SawSignal[0],ExpSignal[0],SinSignal[0],GausSignal[0]]
SignalLabels=[
    1*np.ones(1000),
    2*np.ones(1000),
    3*np.ones(1000),
    4*np.ones(1000),
    5*np.ones(1000)]
SignalsTest=np.array(np.concatenate(Signals).flat)
a=np.array(np.concatenate(a).flat)
b=np.array(np.concatenate(b).flat)
c=np.array(np.concatenate(c).flat)

SignalsTest=SignalsTest.reshape((5000,1500))
SignalLabelsTest=np.array(np.concatenate(SignalLabels).flat)
test_loss, woNoiseAcc = modelNN.evaluate(SignalsTest,  SignalLabelsTest, verbose=2,use_multiprocessing=True,)
#modelNN.evaluate()
#modelNN.predict_batch(BoxSignal[0])
probability_model=tf.keras.Sequential([modelNN,tf.keras.layers.Softmax()])
predictions=probability_model.predict(SignalsTest)

1
2
3
4
5
157/157 - 0s - loss: 0.0701 - accuracy: 0.9746 - 289ms/epoch - 2ms/step
157/157 [==============================] - 0s 955us/step


In [9]:

BoxSignal=Generate('Box',x,fourier=True,N=80,Amount=1000)
SawSignal=Generate('Saw',x,fourier=True,N=80,Amount=1000)
ExpSignal=Generate('Exp',x,fourier=True,N=80,Amount=1000)
SinSignal=Generate('Sin',x,fourier=True,N=80,Amount=1000)
GausSignal=Generate('Gaus',x,fourier=True,N=points,M=80,Amount=1000)
a=[BoxSignal[1],SawSignal[1],ExpSignal[1],SinSignal[1],GausSignal[1]]
b=[BoxSignal[2],SawSignal[2],ExpSignal[2],SinSignal[2],GausSignal[2]]
c=[np.zeros(1000),np.zeros(1000),ExpSignal[3],SinSignal[3],np.zeros(1000)]
Signals=[BoxSignal[0],SawSignal[0],ExpSignal[0],SinSignal[0],GausSignal[0]]
SignalLabels=[
    1*np.ones(1000),
    2*np.ones(1000),
    3*np.ones(1000),
    4*np.ones(1000),
    5*np.ones(1000)]
SignalsTest=np.array(np.concatenate(Signals).flat)
a=np.array(np.concatenate(a).flat)
b=np.array(np.concatenate(b).flat)
c=np.array(np.concatenate(c).flat)

SignalsTest=SignalsTest.reshape((5000,1500))
SignalLabelsTest=np.array(np.concatenate(SignalLabels).flat)
test_loss, woNoiseAcc = modelNN.evaluate(SignalsTest,  SignalLabelsTest, verbose=2,use_multiprocessing=True,)
#modelNN.evaluate()
#modelNN.predict_batch(BoxSignal[0])
probability_model=tf.keras.Sequential([modelNN,tf.keras.layers.Softmax()])
predictions=probability_model.predict(SignalsTest)

1
2
3
4
5
157/157 - 0s - loss: 0.0579 - accuracy: 0.9794 - 171ms/epoch - 1ms/step
157/157 [==============================] - 0s 968us/step


In [10]:

BoxSignal=Generate('Box',x,fourier=True,N=20,Amount=1000)
SawSignal=Generate('Saw',x,fourier=True,N=20,Amount=1000)
ExpSignal=Generate('Exp',x,fourier=True,N=20,Amount=1000)
SinSignal=Generate('Sin',x,fourier=True,N=20,Amount=1000)
GausSignal=Generate('Gaus',x,fourier=True,N=points,M=20,Amount=1000)
a=[BoxSignal[1],SawSignal[1],ExpSignal[1],SinSignal[1],GausSignal[1]]
b=[BoxSignal[2],SawSignal[2],ExpSignal[2],SinSignal[2],GausSignal[2]]
c=[np.zeros(1000),np.zeros(1000),ExpSignal[3],SinSignal[3],np.zeros(1000)]
Signals=[BoxSignal[0],SawSignal[0],ExpSignal[0],SinSignal[0],GausSignal[0]]
SignalLabels=[
    1*np.ones(1000),
    2*np.ones(1000),
    3*np.ones(1000),
    4*np.ones(1000),
    5*np.ones(1000)]
SignalsTest=np.array(np.concatenate(Signals).flat)
a=np.array(np.concatenate(a).flat)
b=np.array(np.concatenate(b).flat)
c=np.array(np.concatenate(c).flat)

SignalsTest=SignalsTest.reshape((5000,1500))
SignalLabelsTest=np.array(np.concatenate(SignalLabels).flat)
test_loss, woNoiseAcc = modelNN.evaluate(SignalsTest,  SignalLabelsTest, verbose=2,use_multiprocessing=True,)
#modelNN.evaluate()
#modelNN.predict_batch(BoxSignal[0])
probability_model=tf.keras.Sequential([modelNN,tf.keras.layers.Softmax()])
predictions=probability_model.predict(SignalsTest)

1
2
3
4
5
157/157 - 0s - loss: 0.2584 - accuracy: 0.9482 - 162ms/epoch - 1ms/step
157/157 [==============================] - 0s 930us/step


In [145]:
len(predictions)

5000

In [23]:
testResults=[]
for i in range(len(predictions)):
    A=np.max(predictions[i])
    maxElement=np.where(predictions[i]==A)
    testResults.append(maxElement[0][0])


In [18]:
len(testResults)

5000

In [24]:
Model1Summ=pd.DataFrame()
Model1Summ['Actual Classifcation']=SignalLabelsTest
Model1Summ['Predicted Classification']=testResults
Model1Summ['a']=a
Model1Summ['b']=b
Model1Summ['c']=c


In [28]:
confusionMatrix=np.zeros((5,5),dtype=float)

In [29]:
confusionMatrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:

#Model1Summ[0:1000]['Predicted Classifcation']==2
box=Model1Summ[0:1000]
saw=Model1Summ[1000:2000]
exp=Model1Summ[2000:3000]
sin=Model1Summ[3000:4000]
gaus=Model1Summ[4000:5000]
for i in range(5):
    signal=Model1Summ[i*1000:(i+1)*1000]
    confusionMatrix[i][0]=len(signal[signal['Predicted Classification']==1])/1000
    confusionMatrix[i][1]=len(signal[signal['Predicted Classification']==2])/1000
    confusionMatrix[i][2]=len(signal[signal['Predicted Classification']==3])/1000
    confusionMatrix[i][3]=len(signal[signal['Predicted Classification']==4])/1000
    confusionMatrix[i][4]=len(signal[signal['Predicted Classification']==5])/1000

In [32]:
confusionMatrix

array([[0.987, 0.   , 0.   , 0.   , 0.013],
       [0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.006, 0.002, 0.992, 0.   , 0.   ],
       [0.   , 0.042, 0.   , 0.958, 0.   ],
       [0.003, 0.   , 0.   , 0.   , 0.997]])

In [33]:
Model1Summ.to_csv('Model3Results.csv')

In [34]:
modelNN.save('Model3TrainedTF')

INFO:tensorflow:Assets written to: Model3TrainedTF\assets
